# Generated by Django 6.0.6 on 2026-06-15 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='threshold',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='assigned_technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
